language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jmy98/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jmy98/react-test npm test -- --coverage

after_success:
  - docker build -t jmy98/multi-client ./client
  - docker build -t jmy98/multi-nginx ./nginx
  - docker build -t jmy98/multi-server ./server
  - docker build -t jmy98/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker hub
  - docker push jmy98/multi-client
  - docker push jmy98/multi-nginx
  - docker push jmy98/multi-server
  - docker push jmy98/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-777225698842'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  
